### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kendelljoseph**

### CODE REVIEW

**Comment by altereagle** [comment]
This is a test comment.

**Comment by altereagle** [comment]
Test comment

**Comment by altereagle** [comment]
This is a test comment

**Review by kendelljoseph — COMMENTED** [review]
This is a test review.

**Review by kendelljoseph — COMMENTED** [review]
This is another test review, ignore this.

**Review by kendelljoseph — COMMENTED** [review]
Another test review. (for the discord bot)

**Review by kendelljoseph — COMMENTED** [review]
another test...

**Review by kendelljoseph — COMMENTED** [review]
This should work now (another test)

**Review by kendelljoseph — COMMENTED** [review]
Okay, just realized i could have been updating the comment instead of making new ones... It's all good now though!

**Comment by kendelljoseph** [comment]
Okay made a tiny legit change, this is all done now! Yay for bots!

**Pull request merged**
