### PR TITLE
https://www.pivotaltracker.com/story/show/149985349

### PR DESCRIPTION
**Pull request by kendelljoseph**
- Added style guide for this [story](https://www.pivotaltracker.com/story/show/149985349).
- Added front end components for this [wireframe](https://www.pivotaltracker.com/story/show/150260811).

---
I went rogue here on this one by creating stuff that didn't have stories. I will retroactively go back and fill in the details soon!

### This is the very last of things that are a part of the setup milestone!

### CODE REVIEW

**Review by hdewey — DISMISSED** [review]
Looks great!

**Comment by grng00ber** [comment]
What's up with the issues? I guess I have a hard time saying it's good if Travis doesn't agree with it.

**Review by deeptronos — COMMENTED** [review]
Yeah, Travis and Code Climate seem to not be satisfied with the changes, what's up with them?

**Comment by kendelljoseph** [comment]
Yea, I've got lots of bugs to fix yet, I saw them but ran out of time to work :).  I'll fix them up tonight.

**Comment by kendelljoseph** [comment]
Travis isn't passing the front end tests for some reason, I cant figure out why but I am going to try switching testing libraries to [this one](https://github.com/GoogleChrome/puppeteer) for front end tests.

**Comment by grng00ber** [comment]
I have seen the struggle with the demo header not loading in travis. I have (with the coaching of Kendell) linted out some SCSS to CSS issues with Fallback colors and Units on "0's". We also commented out a socket IO for the meantime until applicable.

**Review by grng00ber — APPROVED** [review]
Looks fantabulous!

**Pull request merged**
